require_relative 'node'
require_relative 'film'
require_relative 'kevin_bacon'

Liam Neeson = Node.new("Liam Neeson")
Brad Pitt = Node.new("Brad Pitt")
Ryan Reynolds = Node.new("Ryan Reynolds")
Will Smith = Node.new("Will Smith")
Al Pacino = Node.new("Al Pacino")
Robert De Niro = Node.new("Robert De Niro")
Ray Liotta = Node.new("Ray Liotta")
Joe Pesci = Node.new("Joe Pesci")
Samuel Jackson = Node.new("Samuel Jackson")
Jack Nickolson = Node.new("Jack Nickolson")
John Travolta = Node.new("John Travolta")
Kevin Bacon = Node.new("Kevin Bacon")
Leonardo Di Caprio = Node.new("Leonardo Di Caprio")
Mel Gibson = Node.new("Mel Gibson")
Tom Cruise = Node.new("Tom Cruise")
Clint Eastwood = Node.new("Clint Eastwood")
Angelina Jolie = Node.new("Angelina Jolie")
Natalie Portman = Node.new("Natalie Portman")

Goodfellas = Film.new("Goodfellas")
God Father = Film.new("God Father")
Schindler List = Film.new("Schindler List")
Life = Film.new("Life")
Pursuit_of_Happiness = Film.new("Pursuit of Happiness")
Braveheart = Film.new("Braveheart")
Blood Diamond = Film.new("Blood Diamond")
The Shining = Film.new("The Shining")
Gran Torino = Film.new("Gran Torino")
Pulp Fiction = Film.new("Pulp Fiction")
Top Gun = Film.new("Top Gun")
Hollow Man = Film.new("Hollow Man")
V_For_Vendetta = Film.new("V for Vendetta")
